### ISSUE TITLE
iptables rule is not created

### ISSUE THREAD

**Issue by nsychev** [KatharaFramework/NetworkPlugin#8]
Hi!

I'm trying to launch docker-compose network with your plugin. But hosts can't interact with each other.

My host is Ubuntu 20.04, Docker is 20.10.14, docker-compose is 1.29.2. Compose file:

```
version: "3.6"
services:
  relay:
    image: "debian:11-slim"
    cap_add:
      - NET_ADMIN
    networks:
      - internal
  stub:
    image: "debian:11-slim"
    networks:
      - internal
    cap_add:
      - NET_ADMIN
networks:
  internal:
    driver: kathara/katharanp:latest
    ipam:
      driver: "null"
```

Then I'm running bash in each container and executing `ip addr add 10.8.123.1/24 dev eth0` (and .2 for other container).
Then I'm doing `ping 10.8.123.1` from the second one.

**Expected behaviour:** successful ping.

**Actual behaviour:**

Packets are dropping somewhere. Containers receive each other mac addresses (they're shown in `arp -a`).

Latter I launch `iptables -vL` on host and found that there is no accept rule from `kt-...` interface to itself. After adding it manually (`iptables -A FORWARD -i kt-... -o kt-... -j ACCEPT`), it worked.

I don't know how to collect any debug information on plugin, but I'd be glad to provide any useful information.
